### ISSUE TITLE
Support for VS2019

### ISSUE THREAD

**Issue by canro91** [pragmatrix/SaveAllTheTime#2]
Is there any plan to support VS2019?

**Comment by pragmatrix** [comment]
Last time I used VS2019, this version: https://github.com/pragmatrix/SaveAllTheTime/releases/tag/1.4.0.4 seemed to play fine with it.

**Comment by kriewall** [comment]
I get this message when I try to install in VS2019; install option is disabled:

![image](https://user-images.githubusercontent.com/38048622/59382764-4f8c4a80-8d13-11e9-8f02-cf5a8671e9b9.png)

Am I missing something basic?

**Comment by pragmatrix** [comment]
@kriewall and @canro91  Thank you, and my bad, I had tinkered around with a local branch and then completely forgot about it. Here is an update that should be compatible with VS2017 and VS2019 and is quite similar to the version I used for some time now: https://github.com/pragmatrix/SaveAllTheTime/releases/tag/1.4.0.5

Please report back if there are any issues with it.

**Comment by kriewall** [comment]
Thanks @pragmatrix - the new rev is friendlier toward VS2015 but for some reason it still dislikes (at least my version of) VS2019:

![image](https://user-images.githubusercontent.com/38048622/59387497-27561900-8d1e-11e9-8fa1-caddcca29083.png)

Is there a way I can determine which pre-reqs the installer is complaining about?  Happy to provide more info if you need it but I might need some guidance.

**Comment by pragmatrix** [comment]
The pre-requisite dependency version range did not include VS2019 16.1, and I had 16.0 installed, Here is a release that should install with 16.1: https://github.com/pragmatrix/SaveAllTheTime/releases/tag/1.4.0.6

**Comment by kriewall** [comment]
It works!  Thanks for your time to keep this extension alive and kicking.  :)

**Comment by pragmatrix** [comment]
Nothing to thank for, I would have updated the extension the next time I use VS anyways. I am merging the branch and closing the issue hoping it's stable, reopen or create a new issue if not.

**Comment by canro91** [comment]
It worked! Thanks @pragmatrix for keeping this extension alive! I had forgotten to hit Ctrl + S with this extension :)
